{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mon-projet.fullname" . }}-api-secret
  labels:
    {{- include "mon-projet.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.apiSecrets.dbPassword | b64enc | quote }}
{{- end }}
